name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build site
        run: deno run -A ./build.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "ultra2-todo-signals" # deploy project name
          entrypoint: "server.js"
          root: .ultra
          import-map: importMap.server.json
